### ISSUE TITLE
本地跑出问题

### ISSUE THREAD

**Issue by imgblz** [x-dr/wechaty-bot#2]
node app.js
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'wechaty' imported from /wechaty-bot/app.js
    at packageResolve (internal/modules/esm/resolve.js:664:9)
    at moduleResolve (internal/modules/esm/resolve.js:705:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:798:11)
    at Loader.resolve (internal/modules/esm/loader.js:100:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:246:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

**Comment by x-dr** [comment]
> node app.js
> 
> internal/process/esm_loader.js:74
> 
>     internalBinding('errors').triggerUncaughtException(
> 
>                               ^
> 
> 
> 
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'wechaty' imported from /wechaty-bot/app.js
> 
>     at packageResolve (internal/modules/esm/resolve.js:664:9)
> 
>     at moduleResolve (internal/modules/esm/resolve.js:705:18)
> 
>     at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:798:11)
> 
>     at Loader.resolve (internal/modules/esm/loader.js:100:40)
> 
>     at Loader.getModuleJob (internal/modules/esm/loader.js:246:28)
> 
>     at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
> 
>     at link (internal/modules/esm/module_job.js:46:36) {
> 
>   code: 'ERR_MODULE_NOT_FOUND'
> 
> }


npm i 没
